### ISSUE TITLE
Material theme: numbering

### ISSUE THREAD

**Issue by wstaelens** [jmalarcon/MIIS#13]
![image](https://user-images.githubusercontent.com/7447285/42684730-43a2b666-8691-11e8-87cb-65820d8708b3.png)

I've spotted a problem in the Material theme where the numbering per subsection does not restart per new subsection…

(folder) structure  in toc.md:
```
#### [Troubleshooting](/troubleshooting/index.md)
* [General](/troubleshooting/general/index.md)
	* [foo](/troubleshooting/general/foo.md)
* [Email](/troubleshooting/email/index.md)
	* [bar](/troubleshooting/email/bar.md)
* [Printing](/troubleshooting/printing/index.md)
	* [xxx](/troubleshooting/printing/xxx.md)
```
how could this be solved?

**Comment by wstaelens** [comment]
Seem to have found the solution:

Put existing counters in common.css in comment and change with this:

```CSS
/*.miis-toc {
    counter-reset:firstlevel;
}
.miis-toc > ul {
    counter-reset:secondlevel;
}
.miis-toc > ul > li > a:before {
    counter-increment:firstlevel;
    content: counter(firstlevel) ".- ";
}

.miis-toc > ul > li > ul> li > a:before {
    counter-increment:secondlevel;
    content: counter(firstlevel) "." counter(secondlevel) ".- ";
}*/

/* new code */
.miis-toc ul {
    counter-reset: nested-counter;
}

.miis-toc ul li a:before {
  counter-increment:nested-counter;
  content: counters(nested-counter, ".") ") ";
}
```

did not know this was possible with css 3 already!!
